spring.application.name=romashkako
server.port=8888

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:romashkako}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
